export const CLOSE_LOG_IN_MODAL = 'CLOSE_LOG_IN_MODAL';
export const OPEN_LOG_IN_MODAL = 'OPEN_LOG_IN_MODAL';
// export const LOG_IN_FIREBASE = 'LOG_IN_FIREBASE';
export const CHANGE_EMAIL = 'CHANGE_EMAIL';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const DISABLE_LOG_IN_BUTTON = 'DISABLE_LOG_IN_BUTTON';
export const ENABLE_LOG_IN_BUTTON = 'ENABLE_LOG_IN_BUTTON';

// operating reminderlist stepper
export const OPEN_OPERATE_MODAL = 'OPEN_OPERATE_MODAL';
export const GO_OPERATING_STEP = 'GO_OPERATING_STEP';
export const SET_OPERATING_TYPE = 'SET_OPERATING_TYPE';
export const SET_REMINDERLIST_NAMELIST = 'SET_REMINDERLIST_NAMELIST';
export const SET_OPERATE_NAME_INPUT_ERRORTEXT = 'SET_OPERATE_NAME_INPUT_ERRORTEXT';
export const SET_OPERATE_REMINDERLIST_NAME = 'SET_OPERATE_REMINDERLIST_NAME';
export const SET_REMINDERLIST = 'SET_REMINDERLIST';
export const CLOSE_OPERATE_MODAL = 'CLOSE_OPERATE_MODAL';
export const INIT_OPERATE_MODAL_DATA = 'INIT_OPERATE_MODAL_DATA';
export const INIT_OPERATE_MODAL_UI = 'INIT_OPERATE_MODAL_UI';

// reminder editor
export const OPEN_REMINDER_EDITOR = 'OPEN_REMINDER_EDITOR';
export const CLOSE_REMINDER_EDITOR = 'CLOSE_REMINDER_EDITOR';

// createEntity pannel
export const SET_CREATE_ENTITY_TYPE = 'SET_CREATE_ENTITY_TYPE';
export const SET_CREATE_ENTITY_DATE = 'SET_CREATE_ENTITY_DATE';
export const SET_CREATE_ENTITY_PRODUCT = 'SET_CREATE_ENTITY_PRODUCT';
export const SET_CREATE_ENTITY_COUNT = 'SET_CREATE_ENTITY_COUNT';
export const SET_CREATE_ENTITY_UNIT = 'SET_CREATE_ENTITY_UNIT';
export const SET_CREATE_ENTITY_UNITPRICE = 'SET_CREATE_ENTITY_UNITPRICE';
export const SET_CREATE_ENTITY_REMARK = 'SET_CREATE_ENTITY_REMARK';
