export const CLOSE_LOG_IN_MODAL = 'CLOSE_LOG_IN_MODAL';
export const OPEN_LOG_IN_MODAL = 'OPEN_LOG_IN_MODAL';
export const LOG_IN_FIREBASE = 'LOG_IN_FIREBASE';
export const CHANGE_EMAIL = 'CHANGE_EMAIL';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
