export const CLOSE_LOG_IN_MODAL = 'CLOSE_LOG_IN_MODAL';
export const OPEN_LOG_IN_MODAL = 'OPEN_LOG_IN_MODAL';
// export const LOG_IN_FIREBASE = 'LOG_IN_FIREBASE';
export const CHANGE_EMAIL = 'CHANGE_EMAIL';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const DISABLE_LOG_IN_BUTTON = 'DISABLE_LOG_IN_BUTTON';
export const ENABLE_LOG_IN_BUTTON = 'ENABLE_LOG_IN_BUTTON';

// operating reminderlist stepper
export const GO_OPERATING_STEP = 'GO_OPERATING_STEP';
export const SET_OPERATING_TYPE = 'SET_OPERATING_TYPE';
export const SET_REMINDERLIST_NAMELIST = 'SET_REMINDERLIST_NAMELIST';
export const SET_OPERATE_NAME_INPUT_ERRORTEXT = 'SET_OPERATE_NAME_INPUT_ERRORTEXT';
export const SET_OPERATE_REMINDERLIST_NAME = 'SET_OPERATE_REMINDERLIST_NAME';
